language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003177
mono:
  - latest
os:
  - linux
node_js:
  - '7'
before_install:
  - nvm install 7.10.0
  - nvm use 7.10.0
  - npm install compare-obj diff fs path child_process
  - npm install -g z-schema
install:
  - sh script/setup.sh
  - sh script/cibuild.sh
  - sh script/linters.sh
script:
  - node test/integration.js
