language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
mono:
  - latest
os:
  - linux
node_js:
  - '7'
before_install:
  - nvm install 7.10.0
  - nvm use 7.10.0
  - cd test && npm install && cd ../
  - npm install -g z-schema
install:
  - sh script/cibuild.sh
script:
  - node test/integration.js
